In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [23]:
data = pd.read_csv("0000000000002419_training_ccpp_x_y_train.csv")
df = pd.DataFrame(data)
df.head()

     # T      V       AP     RH      EP
0   8.58  38.38  1021.03  84.37  482.26
1  21.79  58.20  1017.21  66.74  446.94
2  16.64  48.92  1011.55  78.76  452.56
3  31.38  71.32  1009.17  60.42  433.44
4   9.20  40.03  1017.05  92.46  480.38

In [24]:
df.describe()

               # T            V           AP           RH           EP
count  7176.000000  7176.000000  7176.000000  7176.000000  7176.000000
mean     19.629712    54.288154  1013.263032    73.275818   454.431293
std       7.475256    12.751468     5.964863    14.625093    17.134571
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.470000    41.740000  1009.010000    63.202500   439.737500
50%      20.315000    52.050000  1012.910000    74.895000   451.740000
75%      25.720000    66.540000  1017.302500    84.925000   468.667500
max      35.770000    81.560000  1033.300000   100.160000   495.760000

In [25]:
def step_gradient(X, Y, learning_rate, m, c):
    m_slope = np.zeros(len(X.iloc[0]))
    c_slope = 0 
    N = len(X)
    for i in range(N):
        x = X.iloc[i]
        y = Y.iloc[i]
        pred = np.dot(m, x) + c
        error = y - pred
        m_slope += (-2 / N) * error * x
        c_slope += (-2 / N) * error
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    return new_m, new_c

def gradient_descent(X, Y, learning_rate, num_iterations):
    m = np.zeros(X.shape[1])
    c = 0
    for i in range(0, num_iterations, 100):
        m, c = step_gradient(X, Y, learning_rate, m, c)
        print(i, "Cost: ", cost(X, Y, m, c))
    return m, c

def cost(X, Y, m, c):
    total_cost = 0
    N = len(X)
    for i in range(N):
        x = X.iloc[i]
        y = Y.iloc[i]
        pred = np.dot(m, x) + c
        total_cost += (1 / N) * ((y - pred) ** 2)
    return total_cost

def score(Y_true, Y_pred):
    u = ((Y_true - Y_pred) ** 2).sum()
    v = ((Y_true - (Y_true.mean())) ** 2).sum()
    return 1 - (u / v)

def feature_scaling(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    return (X - mean) / std

In [26]:
def run():
    data = pd.read_csv("0000000000002419_training_ccpp_x_y_train.csv")
    df = pd.DataFrame(data)
    X = df.iloc[:, :4]
    Y = df.iloc[:, -1]

    X = feature_scaling(X)
    
    x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=2)

    learning_rate = 0.05
    num_iterations = 15000
    m, c = gradient_descent(x_train, y_train, learning_rate, num_iterations)
    print("Trained parameters:", m, c)

    # Make predictions on the training set
    train_predictions = np.dot(x_train, m) + c
    train_score = score(y_train, train_predictions)
    print("Score on training set:", train_score)

    # Make predictions on the test set
    test_predictions = np.dot(x_test, m) + c
    test_score = score(y_test, test_predictions)
    print("Score on test set:", test_score)

    test_data = np.loadtxt("0000000000002419_test_ccpp_x_test.csv", delimiter=",")
    final_predictions = np.dot(test_data, m) + c

    print("Final Predictions:", final_predictions)
    np.savetxt("pred.csv", final_predictions)

    return final_predictions

In [27]:
predictions = run()
np.savetxt("pred.csv", predictions)

0 Cost:  167479.8285625605
100 Cost:  135618.5973422638
200 Cost:  109829.51869026976
300 Cost:  88951.22495204741
400 Cost:  72046.22759993022
500 Cost:  58357.01334562388
600 Cost:  47271.06536454129
700 Cost:  38292.864235975234
800 Cost:  31021.39977489769
900 Cost:  25132.065108365958
1000 Cost:  20362.05370580179
1100 Cost:  16498.567091734116
1200 Cost:  13369.283909029038
1300 Cost:  10834.65189840819
1400 Cost:  8781.651396562134
1500 Cost:  7118.747859419582
1600 Cost:  5771.805817251775
1700 Cost:  4680.780615366426
1800 Cost:  3797.039592350289
1900 Cost:  3081.1927680144304
2000 Cost:  2501.3360351820656
2100 Cost:  2031.6283596805274
2200 Cost:  1651.139453535013
2300 Cost:  1342.9164855722458
2400 Cost:  1093.2281829988192
2500 Cost:  890.9526004462331
2600 Cost:  727.0812467283615
2700 Cost:  594.31745241183
2800 Cost:  486.7510661217246
2900 Cost:  399.5949725495253
3000 Cost:  328.9716826709977
3100 Cost:  271.7404799351925
3200 Cost:  225.35741488513202
3300 Cost:  187.76190555515336
3400 Cost:  157.28488743255826
3500 Cost:  132.5744177076702
3600 Cost:  112.53541683473911
3700 Cost:  96.28086080268956
3800 Cost:  83.09224808554515
3900 Cost:  72.38757877857884
4000 Cost:  63.695418370455045
4100 Cost:  56.6338898907055
4200 Cost:  50.893657903919156
4300 Cost:  46.22414579542592
4400 Cost:  42.42237194429931
4500 Cost:  39.32390713604115
4600 Cost:  36.79555013558611
4700 Cost:  34.72939493800665
4800 Cost:  33.03802525494046
4900 Cost:  31.65062204551256
5000 Cost:  30.509810601979062
5100 Cost:  29.56910666722659
5200 Cost:  28.79084776344699
5300 Cost:  28.144517539327524
5400 Cost:  27.605388461215234
5500 Cost:  27.153422362942496
5600 Cost:  26.77237986194674
5700 Cost:  26.449098958351765
5800 Cost:  26.17291067381729
5900 Cost:  25.935165694328962
6000 Cost:  25.72885092798401
6100 Cost:  25.548278895720575
6200 Cost:  25.388836118483173
6300 Cost:  25.24677929317386
6400 Cost:  25.11907017909074
6500 Cost:  25.003241841325593
6600 Cost:  24.8972902946468
6700 Cost:  24.799586723010172
6800 Cost:  24.708806366454457
6900 Cost:  24.623870909596466
7000 Cost:  24.54390180734434
7100 Cost:  24.468182470583564
7200 Cost:  24.39612762918867
7300 Cost:  24.32725850933418
7400 Cost:  24.261182720983935
7500 Cost:  24.197577961163134
7600 Cost:  24.136178808488243
7700 Cost:  24.076766022042577
7800 Cost:  24.019157869154608
7900 Cost:  23.963203096925938
8000 Cost:  23.908775235499377
8100 Cost:  23.85576798031192
8200 Cost:  23.804091448564233
8300 Cost:  23.75366914402592
8400 Cost:  23.70443549578717
8500 Cost:  23.65633386208274
8600 Cost:  23.609314910980732
8700 Cost:  23.563335306475643
8800 Cost:  23.518356642085987
8900 Cost:  23.474344575046004
9000 Cost:  23.43126812308544
9100 Cost:  23.389099092998112
9200 Cost:  23.347811616049064
9300 Cost:  23.307381769997395
9400 Cost:  23.2677872713529
9500 Cost:  23.229007224586237
9600 Cost:  23.191021917533238
9700 Cost:  23.15381265427365
9800 Cost:  23.117361618414733
9900 Cost:  23.081651761051617
10000 Cost:  23.04666670876136
10100 Cost:  23.012390687864933
10200 Cost:  22.978808461905864
10300 Cost:  22.945905279870825
10400 Cost:  22.913666833145907
10500 Cost:  22.882079219580767
10600 Cost:  22.85112891334039
10700 Cost:  22.82080273947471
10800 Cost:  22.791087852336883
10900 Cost:  22.761971717143478
11000 Cost:  22.73344209410801
11100 Cost:  22.70548702467763
11200 Cost:  22.678094819501467
11300 Cost:  22.651254047819158
11400 Cost:  22.624953528022292
11500 Cost:  22.599182319186458
11600 Cost:  22.573929713407566
11700 Cost:  22.54918522880946
11800 Cost:  22.52493860311201
11900 Cost:  22.501179787671735
12000 Cost:  22.477898941921183
12100 Cost:  22.455086428147663
12200 Cost:  22.432732806563525
12300 Cost:  22.410828830626564
12400 Cost:  22.38936544257894
12500 Cost:  22.368333769176523
12600 Cost:  22.347725117588258
12700 Cost:  22.32753097144504
12800 Cost:  22.30774298702381
12900 Cost:  22.28835298955487
13000 Cost:  22.269352969640256
13100 Cost:  22.250735079775403
13200 Cost:  22.232491630966614
13300 Cost:  22.214615089436702
13400 Cost:  22.19709807341509
13500 Cost:  22.179933350006532
13600 Cost:  22.163113832134496
13700 Cost:  22.146632575556318
13800 Cost:  22.130482775946362
13900 Cost:  22.114657766044783
14000 Cost:  22.09915101286881
14100 Cost:  22.083956114986165
14200 Cost:  22.069066799846354
14300 Cost:  22.05447692116851
14400 Cost:  22.040180456386018
14500 Cost:  22.02617150414433
14600 Cost:  22.012444281850158
14700 Cost:  21.998993123273394
14800 Cost:  21.985812476197307
14900 Cost:  21.972896900117707
Trained parameters: # T   -13.033618
 V     -4.324169
 AP     0.665595
 RH    -1.780404
Name: 1947, dtype: float64 454.4201657674325
Score on training set: 0.9251092378248247
Score on test set: 0.9314137640646947
Final Predictions: [632.39930367 660.34568246 308.14914835 ... 359.01075271 521.79500888
 436.96493312]